# Generated by Django 2.0.6 on 2020-01-08 07:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('depart', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_number', models.IntegerField(help_text='If you are not student type 12345')),
                ('phone_number', models.IntegerField()),
                ('role', models.CharField(choices=[('-', '---------'), ('HOD', 'HOD'), ('supervisor', 'supervisor'), ('dean', 'dean'), ('cordinator', 'cordinator'), ('principle', 'principle'), ('lecturor', 'lecturor'), ('student', 'student')], max_length=20)),
                ('image', models.ImageField(blank=True, upload_to='images_profiles')),
                ('department_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to='depart.Department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
