# Generated by Django 2.0.6 on 2020-01-08 07:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('commented_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='file', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=50)),
                ('group_email', models.EmailField(max_length=250)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group', to='depart.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_number', models.IntegerField()),
                ('member_names', models.CharField(max_length=250)),
                ('member_phone_number', models.IntegerField()),
                ('member_email', models.EmailField(max_length=250)),
                ('department_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member', to='depart.Department')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member', to='depart.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_percentage', models.IntegerField()),
                ('file_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='depart.Files')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=500)),
                ('project_description', models.TextField(max_length=10000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='depart.Department')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='depart.Group')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=250)),
                ('description', models.FileField(upload_to='store/')),
                ('technology', models.CharField(max_length=250)),
                ('category', models.CharField(max_length=100)),
                ('member_1', models.CharField(max_length=100)),
                ('member_2', models.CharField(max_length=100)),
                ('member_3', models.CharField(max_length=100)),
                ('marks', models.CharField(max_length=50)),
                ('years', models.CharField(max_length=50)),
                ('hosted_link', models.URLField(blank=True, max_length=128, unique=True)),
                ('stored_on', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectstore', to='depart.Department')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=450)),
            ],
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supervisor_name', models.CharField(max_length=250, null=True)),
                ('supervisor_email', models.EmailField(max_length=250)),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisors', to='depart.Department')),
            ],
        ),
        migrations.AddField(
            model_name='projectstore',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectstore', to='depart.School'),
        ),
        migrations.AddField(
            model_name='projectstore',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectstore', to='depart.Supervisor'),
        ),
        migrations.AddField(
            model_name='group',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group', to='depart.Supervisor'),
        ),
        migrations.AddField(
            model_name='department',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department', to='depart.School'),
        ),
        migrations.AddField(
            model_name='comments',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='depart.ProjectStore'),
        ),
        migrations.AddField(
            model_name='comments',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
