# Generated by Django 2.0.6 on 2020-01-03 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file',
            field=models.FileField(upload_to='files'),
        ),
    ]
