# Generated by Django 2.0.6 on 2020-01-04 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depart', '0002_auto_20200103_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
