# Generated by Django 2.0.6 on 2019-09-18 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('depart', '0003_auto_20190911_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userprofile',
            fields=[
                ('reg_number', models.IntegerField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=250)),
                ('department_name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='member',
            name='reg_number',
            field=models.IntegerField(),
        ),
    ]
