# Generated by Django 2.0.6 on 2019-09-18 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('depart', '0004_auto_20190918_1612'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_name',
            new_name='user_names',
        ),
    ]
