# Generated by Django 2.0.6 on 2020-01-04 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depart', '0004_auto_20200104_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file',
            field=models.FileField(upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='projectstore',
            name='description',
            field=models.FileField(upload_to='store/'),
        ),
    ]
