# Generated by Django 2.0.6 on 2019-09-18 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depart', '0005_auto_20190918_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='student',
            field=models.BooleanField(default=False),
        ),
    ]
