# Generated by Django 2.0.6 on 2020-01-04 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('depart', '0005_auto_20200104_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='sender',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='file', to=settings.AUTH_USER_MODEL),
        ),
    ]
