# Generated by Django 2.0.6 on 2020-01-04 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depart', '0006_auto_20200104_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
