# Generated by Django 2.0.6 on 2019-10-05 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('depart', '0006_userprofile_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='file',
            field=models.FileField(default='no file uploaded', null=True, upload_to='files/'),
        ),
        migrations.AddField(
            model_name='files',
            name='message_id',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='file', to='depart.Message'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_description',
            field=models.TextField(max_length=10000),
        ),
    ]
