# Generated by Django 2.0.6 on 2019-10-05 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('depart', '0007_auto_20191005_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='message_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='file', to='depart.Message'),
        ),
    ]
