# Generated by Django 2.0.6 on 2020-01-04 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('depart', '0007_auto_20200104_1512'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectstore',
            old_name='title',
            new_name='project',
        ),
    ]
