# Generated by Django 2.0.6 on 2020-01-04 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depart', '0008_auto_20200104_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectstore',
            name='project',
            field=models.CharField(max_length=250),
        ),
    ]
