# Generated by Django 2.0.6 on 2019-10-05 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depart', '0008_auto_20191005_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file',
            field=models.FileField(null=True, upload_to='files/'),
        ),
    ]
