# Generated by Django 2.0.6 on 2020-01-04 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depart', '0009_auto_20200104_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectstore',
            name='marks',
            field=models.CharField(default=50, max_length=50),
            preserve_default=False,
        ),
    ]
